fix: improve cache clearing function with error handling

diff --git a/commands/web/woodoo_components/functions b/commands/web/woodoo_components/functions
--- a/commands/web/woodoo_components/functions
+++ b/commands/web/woodoo_components/functions
@@ -9,8 +9,12 @@ function hyvaConfigGenerate() {
 
 # This function runs the Magento command to flush the cache.
 function clearCache() {
-    "${DDEV_COMPOSER_ROOT}"/bin/magento cache:flush
-    echo -e "\n${txtgrn}Cache cleared${txtrst}"
+    if "${DDEV_COMPOSER_ROOT}"/bin/magento cache:flush; then
+        echo -e "\n${txtgrn}Cache cleared${txtrst}"
+    else
+        echo -e "\n${txtred}Failed to clear cache${txtrst}"
+        exit 1
+    fi
 }
 
 # This function removes the static files and view preprocessed files generated by Magento.
